<template>
  <div class="loadingio-spinner-ellipsis-wcjypm16m3e">
    <div class="ldio-u7k78jpm9w">
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
    </div>
  </div>
</template>

<style scoped>
@keyframes ldio-u7k78jpm9w {
  0% {
    transform: translate(12px, 80px) scale(0);
  }
  25% {
    transform: translate(12px, 80px) scale(0);
  }
  50% {
    transform: translate(12px, 80px) scale(1);
  }
  75% {
    transform: translate(80px, 80px) scale(1);
  }
  100% {
    transform: translate(148px, 80px) scale(1);
  }
}
@keyframes ldio-u7k78jpm9w-r {
  0% {
    transform: translate(148px, 80px) scale(1);
  }
  100% {
    transform: translate(148px, 80px) scale(0);
  }
}
@keyframes ldio-u7k78jpm9w-c {
  0% {
    background: #00aeec;
  }
  25% {
    background: #00aeec;
  }
  50% {
    background: #e6a430;
  }
  75% {
    background: #262470;
  }
  100% {
    background: #00aeec;
  }
}
.ldio-u7k78jpm9w div {
  position: absolute;
  width: 40px;
  height: 40px;
  border-radius: 50%;
  transform: translate(80px, 80px) scale(1);
  background: #00aeec;
  animation: ldio-u7k78jpm9w 1s infinite cubic-bezier(0, 0.5, 0.5, 1);
}
.ldio-u7k78jpm9w div:nth-child(1) {
  background: #262470;
  transform: translate(148px, 80px) scale(1);
  animation: ldio-u7k78jpm9w-r 0.25s infinite cubic-bezier(0, 0.5, 0.5, 1),
    ldio-u7k78jpm9w-c 1s infinite step-start;
}
.ldio-u7k78jpm9w div:nth-child(2) {
  animation-delay: -0.25s;
  background: #00aeec;
}
.ldio-u7k78jpm9w div:nth-child(3) {
  animation-delay: -0.5s;
  background: #262470;
}
.ldio-u7k78jpm9w div:nth-child(4) {
  animation-delay: -0.75s;
  background: #e6a430;
}
.ldio-u7k78jpm9w div:nth-child(5) {
  animation-delay: -1s;
  background: #00aeec;
}
.loadingio-spinner-ellipsis-wcjypm16m3e {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: transparent;
}
.ldio-u7k78jpm9w {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-u7k78jpm9w div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>
